[GOOGLE_APPLICATION_CREDENTIALS]
type = "service_account"
project_id = "text-to-speech-445303"
private_key_id = "6ddc5932a2962145338e0570f6f1c449e1cef590"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCzWgmH3Z1ZmyRV
nRYD2C9RvqpvHDfkPWhlL8qMfj29sM8rlcl6Rpmhzd4OTVpZhhpI4rXX59Cxsmeb
ZGHNJPuh9YsB8at9dD0Z/LbEBx/dnD+s1z3+gPAkQnGJo507QzPHYGl6RJMnDT3x
Mxi6exlR35gqavD2pZRwOaCGOevIli+6j6iIN8hStE94Df67RlBXVm8l1LCDDa7G
+J3dJv0nckEr0mGjlOQ+NUsx5e8ZUx9RczXphDWLiIczY2+bPKcSL2BpbxrrJeCh
bwc3LMM/+AcvY8PdZOv7nSxCWOP+A+XQJlxgoncKiKwCdvGbe+oaqppoAGpqKm30
DRO0Zd3nAgMBAAECggEAFdV54DgYJhwfR0DmuN8Xm6GqM/lBIKBigMxZodLjMfWV
XZ6ljCTjd8bifTvo1N82J0taNzI5viLplAmbZ72p2I9WNeK1gtdPckYepddMMiQJ
vcE9Aypakb94/PhAdZd6dTov0mUIw7H2qXy+n5fJfvsea4OLWYDSL6YEUcg5WQ4j
RrNR51cJFiAGtrXGziZXcbWFuwQtMKosUBuX808atCrK1b6jEu2Kzsc6pHlaorI3
w91/K2JIuxgw95V0LJ8spuoVM4QTm8tzjQz/wgIwzUsWzuWGa2NdoGeTS65944EK
fxX+OXpn8VOttl9+hamxN3tPT6i4W9eXR4omjzizoQKBgQDkydZfARUsBftC9K6c
Kit40JNwEAvQ59mk7XNvhXBwOW5VLm0QyEq8p3vFOHdww3JIbGEIEm1X/mY2/Pbf
pMhYGTs5hyceb9wZTiz45UoP58Fh3Q7SrDx/E4Z+TNxlbFlviVhHpgz3znxV54b0
9Q83UkMGboarg6eNolEQPo6xsQKBgQDIrvKpHW6kj/D4iBAdJNFKVOvOu/c4wmxX
TGew+LZ0LpndJgCs/fdusZoFmqsc4sxHP/GDc64kC3Zxdjs96gEN4v5PHMRGtqLn
qdUNW2VHaPzaoQ06ffLh8hJjtliaWzzwT0gY9btjipvsiaQt++ht6HbDA9E2yoh3
VmJI360XFwKBgQCShuYhwHrD0Czk6/psj+F5pfPXgJ9gsyzEIUOeOBMT/OQ579rw
NacP/iAZ5pkwgixOUAMw/UREZ+0k6IxgHZQmQDqbFIEsUC3hkxzgZ1EwsJg8yiw1
JxQzutiXSTiaSHNbKNZ+RM3nY7pj9j2L4utU3f2JP/5GGLKV1lAenEIdcQKBgAhi
Vrz9/8tcQCMB/DpbeWrzlU5zx+ZVKRWUmZhpK6Y69C6rEcgobBfxz4+AYLm6N/Ka
F0r4oEPdPruKxvrVNeoQm7NOblzN8IxhKgd+1AJhvn6bz+Ors2QBKweDbLw2J5ua
lFaGnaeQ+Oau8W8CYTmGRr/q/uidGYpyz3Rf8+lNAoGBAK8pTFvu/xoQUnpKT5mH
71UkDEv2G5W4Jt0PbUOuiMZjA/hKaxH3PgaHPaLaMuxXd+RlTDbXOBbPsQP+oAiW
edEPXrpuvogTl83IfvxcFjl8pRmTk1fLulFhN49KxrUpdhMvOxFmYmiizUeaN3cw
jRZ+C8c9tdAOosGS+f15nEvi
-----END PRIVATE KEY-----"""
client_email = "tts-service-account@text-to-speech-445303.iam.gserviceaccount.com"
client_id = "114840934838733244072"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tts-service-account%40text-to-speech-445303.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
